name       : appdata-tools
version    : 0.1.8
release    : 5
source     :
    - http://people.freedesktop.org/~hughsient/releases/appdata-tools-0.1.8.tar.xz : 401583d27f0f91bbc03de09f53efd4bf86b20da37d6930ff7bff297d7f1e5461
homepage   : http://people.freedesktop.org/~hughsient
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : appdata validation tools
description: |
    appdata validation tools
builddeps  :
    - pkgconfig(appstream-glib)
patterns   :
    - /*
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
